baseURL = 'https://rang-jiao.github.io'
languageCode = 'zh-cn'
title = '交讓所生'
subtitle = "求其诚者，非归饷也不可"  # 副标题
imageUrl = "/images/avatar.jpg"  # 头像路径
imageTitle = "我的头像"
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  math = true


[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 40  # 权重越小越靠左

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10

  [[menu.main]]
    identifier = "links"
    name = "友链"
    url = "/links/"
    weight = 30
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20 
# Markdown渲染配置（关键添加）
[markup]
  defaultMarkdownHandler = 'goldmark'
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许HTML渲染（如果需要在Markdown中插入HTML）
    
    [markup.goldmark.extensions]
      typographer = true
      table = true
      taskList = true
      strikethrough = true
      linkify = true

    [markup.highlight]
      style = 'catppuccin-latte'  # 代码高亮主题
      lineNos = true    # 显示行号
      codeFences = ture # 启用代码围栏